= Thai Coconut Pudding

link:./README.me[&larrhk; Back to Dessert Recipes]

This traditional Thai coconut pudding is rich and creamy, offering a soothing contrast to the bold and spicy flavors of Thai cuisine. Made with coconut milk and egg yolks, it delivers a smooth and velvety texture that makes it a perfect dessert for any Thai meal.

Adapted from _Thai Kitchen by McCormick_

== Ingredients

* 1/2 cup flour
* 1/2 cup sugar
* Pinch of salt
* 6 egg yolks
* 3 cans coconut milk

== Instructions

1. Mix the flour, sugar, and salt in a heavy saucepan. Add the egg yolks and mix with a wire whisk until well blended. The mixture will be very thick.
2. Gradually whisk in 1/2 can of coconut milk. Cook on medium heat for 2 to 3 minutes, whisking constantly.
3. Meanwhile, bring the remaining coconut milk to a simmer in a small saucepan.
4. Gradually add the hot coconut milk to the flour and egg mixture, whisking until well blended. The mixture might be lumpy at first, but continue to whisk until smooth.
5. Simmer for 7 to 10 minutes or until very thick, whisking constantly.
6. Serve warm.
