= Very Strawberry Cupcakes

[&larrhk; Back to Desserts](./README.md)

These Very Strawberry Cupcakes are adorned with a tangy and delicious strawberry cream cheese frosting. Packed with flavor from both fresh and freeze-dried strawberries, they deliver a natural and vibrant strawberry taste without any artificial flavor or coloring.

Adapted from _Wild Wild Whisk_, Trang Doan

== Ingredients

=== Cupcakes
* 0.08 cup freeze-dried strawberry powder (1/2 oz)
* 0.5 cup all-purpose flour
* 0.22 cup granulated sugar
* 0.08 teaspoon kosher salt
* 0.33 teaspoon baking powder
* 0.08 teaspoon baking soda
* 0.17 cup pureed strawberry (4 oz)
* 0.11 cup buttermilk (room temperature)
* 0.08 cup vegetable oil
* 0.33 large egg (room temperature)
* 0.17 teaspoon pure vanilla extract

=== Frosting
* 2.67 oz cream cheese (room temperature)
* 2.67 oz unsalted butter (room temperature)
* 0.17 teaspoon pure vanilla extract
* 0.33 cup powdered sugar
* 0.08 cup freeze-dried strawberry powder (1/2 oz)

== Instructions

. Prepare the strawberry powder:
  * Add 1 oz of freeze-dried strawberries to a food processor and process until a powder forms. This should yield 1/2 cup. Use 1/4 cup for the cupcake batter and the remaining 1/4 cup for the strawberry cream cheese frosting.

. Make the cupcakes:
  1. Preheat oven to 350°F and line a muffin pan with cupcake liners. Set aside.
  2. Add 1/4 cup of strawberry powder to a small mixing bowl along with the flour, sugar, salt, baking powder, and baking soda. Mix with a whisk to distribute evenly. Set aside.
  3. In the same food processor used previously for the freeze-dried strawberries, puree the fresh strawberries. Add the strawberry puree to a medium mixing bowl along with the buttermilk, vegetable oil, egg, and vanilla extract. Whisk until smooth.
  4. Add the flour mixture to the wet ingredient mixture and fold until just combined.
  5. Use a large ice cream scoop to divide the batter into the prepared muffin pan, filling each cavity with about 1/4 cup of batter.
  6. Bake in the middle oven rack for 16-17 minutes, until a toothpick inserted in the center of a cupcake comes out clean. Remove from the oven and allow to cool in the pan until cool to the touch, then transfer to a wire rack to cool completely.

. Make the frosting:
  1. Allow the cream cheese and butter to come to room temperature and soften. Cut them into small cubes to speed up the process.
  2. In a stand mixer bowl, add softened butter and cream cheese along with the vanilla extract. Mix with the whisk attachment at medium-low speed, gradually increasing to medium-high, and beat until thoroughly combined.
  3. Stop the mixer to add the powdered sugar and the remaining 1/4 cup of strawberry powder. Mix at low speed to incorporate the powder mixture into the cream mixture, then gradually increase to medium-high speed and beat until thoroughly combined and fluffy.
  4. Add a piping tip of your choice to a pastry bag, fill with the frosting, and frost the cooled cupcakes.
