= Blackened Tilapia

link:./README.md[&larrhk; Back to Seafood Recipes]

An array of savory spices coat this easy blackened tilapia, served on white bread to soak up the delicious juices.

== Ingredients
* 3 tablespoons paprika
* 1 tablespoon onion powder
* 1 pinch garlic powder
* 1 teaspoon ground white pepper
* 1 teaspoon ground black pepper
* 1 teaspoon cayenne pepper, or to taste
* 1 teaspoon dried oregano
* 1 teaspoon dried thyme
* 1/2 teaspoon celery seed
* 1 tablespoon kosher salt, or to taste
* 1 pound tilapia fillets
* 1 lemon, cut into wedges
* 4 slices white bread
* 1 tablespoon vegetable oil

== Instructions
. Prepare Spice Blend:
.. In a small bowl or jar with a lid, mix together the paprika, onion powder, garlic powder, white pepper, black pepper, cayenne pepper, oregano, thyme, celery seed, and kosher salt.
. Season the Fish:
.. Coat the tilapia fillets with the spice mixture and allow them to sit at room temperature for no longer than 30 minutes.
. Cook the Tilapia:
.. Heat a heavy skillet over high heat. Add the vegetable oil and heat until it is almost smoking.
.. Place the fillets in the pan and cook for about 3 minutes per side, or until the fish is opaque and flakes easily with a fork.
. Serve:
.. Remove the tilapia from the pan and place onto slices of white bread. Pour the pan juices over them and squeeze lemon juice all over.
.. Serve immediately with lemon wedges on the side.