= Caprese Stuffed Chicken Breasts

link:./README.me[&larrhk; Back to Poultry Recipes]

This Caprese Stuffed Chicken Breast recipe is an easy and healthy dinner that combines the classic flavors of mozzarella, basil, and sun-dried tomatoes. It's a delicious dish that is sure to impress your dinner guests.

== Ingredients

* 4 (4-ounce) boneless skinless chicken breasts
* 4 ounces mozzarella cheese
* 1/4 cup fresh basil leaves
* 1/4 cup sun-dried tomatoes, jarred in olive oil (~1 oz)
* Salt and pepper, to taste
* 1 tablespoon olive oil
* 2 tablespoons balsamic glaze

== Instructions

1. Preheat the oven to 375°F and spray a baking sheet with nonstick cooking spray.
2. Prepare the chicken breasts by laying them flat on a cutting board. Using a meat tenderizer, pound the chicken until it flattens out and is the same thickness all around, about 1/2 inch thick.
3. Season both sides of the chicken breasts with salt and pepper, to taste.
4. Place about 1 ounce of mozzarella cheese, a few basil leaves, and a tablespoon of sun-dried tomatoes in the center of each chicken breast.
5. Roll each chicken breast tightly and secure it with 2 pieces of baker’s twine.
6. Place the stuffed chicken breasts on the prepared baking sheet and drizzle with olive oil. Bake at 375°F for about 30-40 minutes, or until the chicken is fully cooked.
7. Serve with a drizzle of balsamic glaze.
