= Extra Crispy Oven-Fried Chicken Thighs

link:./README.me[&larrhk; Back to Poultry Recipes]

Recipe for oven-fried chicken thighs that taste just like pan-fried or even deep-fried, but without the greasy mess and extra calories. Perfect for a quick and delicious meal.

== Ingredients
* 2 bone-in, skin-on chicken thighs (about 3 lbs, trimmed)
* 1/4 teaspoon baking powder (do NOT use baking soda, it's NOT the same)
* 1/2 teaspoon kosher salt (plus more to taste)
* 1/2 teaspoon sweet paprika
* 1/4 teaspoon black pepper
* 1 tablespoon Buffalo wing sauce (plus more to taste)

== Instructions
1. Preheat the oven to 450°F.
2. Dry the chicken thighs with paper towels thoroughly. Sprinkle on the salt, paprika, pepper, and baking powder, and gently rub all over the chicken to ensure even coverage.
3. Place the chicken thighs on a cooling rack over a large baking sheet lined with aluminum foil or parchment paper (optional, for easier cleanup). Leave some space between the pieces.
4. Place the baking sheet in the oven and switch the oven to 425°F convection. Bake for 30 minutes for moderate crispiness and supreme juiciness, or for 35-40 minutes for ultimate crispiness and fall-off-the-bone tenderness.
5. Remove the thighs from the oven and let rest for 5 minutes to retain the skin’s crispiness.
6. Toss the thighs in Buffalo wing sauce, or any other sauce of your choice, and serve. Alternatively, serve with a dipping sauce on the side.

== Notes
* For a non-convection oven: Adjust oven racks to upper-middle and lower-middle positions and preheat the oven to 250°F. Arrange chicken thighs in a single layer on a wire rack over a baking sheet. Bake on the lower-middle oven rack for 30 minutes, then move to the upper-middle rack, increase the oven temperature to 425°F, and roast until golden brown and crisp, 40-50 minutes longer, rotating the sheet halfway through baking. Let the thighs rest for 5 minutes before tossing in sauce or serving.
* You can use a mix of hot and BBQ sauce or serve with a white dipping sauce like homemade ranch. Apply salt before or after baking, depending on your preference for browning and crispiness.
