= Low Carb Crackers

link:./README.md(&larrhk; Back to Bread Recipes)

These low-carb crackers are a flavorful and crunchy snack option, made with almond flour, cheddar, and parmesan, perfect for those following a low-carb or keto diet.

Adapted from _KetoConnect_, Mia Henderson

== Ingredients

* 1 cup almond flour (120g)
* 3/4 cup cheddar cheese (70g)
* 1/4 cup parmesan cheese (23g)
* 1/8 teaspoon pink Himalayan salt
* 1/4 teaspoon garlic powder (optional)
* Herbs of choice (e.g., rosemary, oregano, thyme)

== Instructions

1. Preheat the oven to 180°C/350°F. Line a large baking sheet with parchment paper.
2. Add the almond flour, cheddar, parmesan, salt, and garlic powder (if using) to a food processor and blend well until it forms a dough. If the dough is too crumbly or isn’t coming together, microwave the mixture for 20-30 seconds to allow the cheese to melt, then return it back to the blender and blend. The dough might stay a bit crumbly, but it must stick together if you pinch it with your fingers.
3. Transfer the dough to a bowl, add your desired herb(s) if using, and knead well with a spatula or wooden spoon.
4. Place the dough onto a piece of parchment paper, and fold it over the dough. Use a rolling pin to roll out the dough to about 1/4 inch thick.
5. Cut the dough into even squares with a pizza cutter and then sprinkle with flakey salt on top.
6. Bake for 10-12 minutes, or until golden around the edges.
7. Remove from the oven and allow to cool completely.
8. Store crackers in an airtight container at room temperature.
