= Green Chili Tomatillo Salsa

link:./README.me[&larrhk; Back to Sauces &amp; Seasonings]

Green Chili Tomatillo Salsa is a smoky and spicy salsa with a burst of citrus and fresh cilantro. This homemade version is perfect for adding a kick to your favorite Mexican dishes.

Adapted from _Dinner then Dessert_, Sabrina Snyder

image::https://badgen.net/badge/verified/delicious/228B22[Verified Delicious]

== Ingredients
* 1 pound tomatillos, halved
* 1 vine tomato, halved
* 1 jalapeño, deseeded
* 1/2 red onion, cut into wedges
* 2 cloves garlic
* 1/2 teaspoon kosher salt
* 1/4 teaspoon coarse ground black pepper
* 1 teaspoon cumin
* 1/2 teaspoon dried oregano
* 1 tablespoon lemon juice
* 1 tablespoon lime juice
* 1/4 cup fresh cilantro

== Instructions
. Preheat your oven to 450°F.
. Place the tomatillos, tomato, jalapeño, and red onion on a baking sheet and roast for 25-30 minutes until they start to char.
. Add the roasted vegetables along with the garlic, salt, black pepper, cumin, oregano, lemon juice, lime juice, and cilantro to a food processor or blender.
. Pulse the mixture until slightly chunky, about 10-15 seconds.
. Serve the salsa fresh or store it in the refrigerator for later use.
