= Stuffed Mushrooms with Goat Cheese and Pine Nuts

link:./README.md[&larrhk; Back to Vegetarian Recipes]

Make-Ahead Stuffed Mushrooms with Goat Cheese and Pine Nuts are a great Thanksgiving appetizer that you can make the day before!

Adapted from _Food Folks and Fun_, Jillian Wade

image::https://badgen.net/badge/verified/delicious/228B22[Verified Delicious]

== Ingredients
* 3 tablespoons olive oil, separated
* 1 small shallot, diced small
* 1/4 cup white cooking wine (or substitute with chicken broth or white grape juice)
* 1 pound white button mushrooms
* Salt, to taste
* 4 ounces goat cheese, softened
* 1 tablespoon freshly-squeezed lemon juice
* Zest from 1 lemon
* 1 teaspoon Worcestershire sauce
* 1/4 teaspoon freshly ground black pepper
* 1/4 teaspoon garlic powder
* 2 tablespoons chopped fresh herbs (such as parsley, thyme, or rosemary)
* 1/4 cup pine nuts, toasted
* 1/4 cup panko breadcrumbs

== For Garnish
* Chopped fresh herbs
* Toasted pine nuts
* Lemon zest

== Instructions
. Preheat the oven to 400°F (200°C) and move the oven rack to the upper-middle position.
. Lightly spray a baking sheet or 3-quart baking dish with nonstick cooking spray.
. In a medium non-stick skillet, add 1 teaspoon of olive oil and preheat the pan over medium heat. Add the diced shallots and cook, stirring often, until softened and golden, about 7-8 minutes. Stir in the white cooking wine and cook until all the liquid is evaporated, about 3-5 minutes.
. Meanwhile, rinse the mushrooms, pat them dry, and remove and discard the stems. Place the mushrooms on the baking sheet and brush with 2 tablespoons of olive oil, then sprinkle lightly with salt.
. In a small bowl, combine the caramelized shallots, goat cheese, lemon juice, lemon zest, Worcestershire sauce, pepper, garlic powder, chopped herbs, pine nuts, and panko breadcrumbs. Mix until creamy and well combined.
. Fill each mushroom with a heaping teaspoon of the filling.
. Brush the tops of the mushrooms with the remaining 2 teaspoons of olive oil.
. Bake for 15-20 minutes, or until the tops of the stuffed mushrooms are browned.
. Let cool for a couple of minutes, then garnish with chopped herbs, lemon zest, and toasted pine nuts. Serve.
